FROM registry.getech.cn/mfa/mfa-base:1.2

COPY requirements.txt /

RUN pip install -r /requirements.txt -i https://pypi.douban.com/simple

COPY . /mfa

WORKDIR /mfa

VOLUME /mfa/app/config

RUN sed -i "s@http://deb.debian.org@http://mirrors.aliyun.com@g" /etc/apt/sources.list \
	&& apt-get update \
	&& apt-get install htop apt-utils libaio1 \
    && pip install uwsgi==2.0.18 -i https://pypi.douban.com/simple \
    && mkdir log \
    && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo 'Asia/Shanghai' >/etc/timezone \
    && ln -sfT /dev/stdout "/mfa/servers.log" \
    && mkdir -p /opt/oracle \
	&& cd /opt/oracle \
	&& mv /mfa/sys_lib/instantclient_19_8 /opt/oracle/instantclient_19_8 \
	&& sh -c "echo /opt/oracle/instantclient_19_8 > /etc/ld.so.conf.d/oracle-instantclient.conf" \
	&& ldconfig \
	&& export LD_LIBRARY_PATH=/opt/oracle/instantclient_19_6:$LD_LIBRARY_PATH

EXPOSE 5000

CMD ["uwsgi", "--ini", "/mfa/uwsgi.ini"]