FROM python:3.6

COPY requirements.txt /

RUN pip install -r /requirements.txt -i https://pypi.douban.com/simple

COPY . /mfa

WORKDIR /mfa

VOLUME /mfa/app/config

RUN sed -i "s@http://deb.debian.org@http://mirrors.aliyun.com@g" /etc/apt/sources.list \
	&& apt-get update \
	&& apt-get install htop \
    && pip install uwsgi==2.0.18 -i https://pypi.douban.com/simple \
    && mkdir log \
    && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo 'Asia/Shanghai' >/etc/timezone \
    && ln -sfT /dev/stdout "/mfa/servers.log"

EXPOSE 5000

CMD ["uwsgi", "--ini", "/mfa/uwsgi.ini"]